### PR TITLE
String spaces

### PR DESCRIPTION
**Pull request by sowmith1729**
Modified ast.h to add a new token type for string, char type for quotes,
and a parse state for string.
Modified get_char_type and get_token to support spaces in strings
```slog
(edge "well string")
(edge "well another string)")
(edge "yet another ! ? string")
```
Goes through successfully

Updated repl_and_runslog.md.

### CODE REVIEW

**Comment by StarGazerM** [comment]
can you add a CI case for this?

**Comment by sowmith1999** [comment]
Added this simple test, Please let me know if you have any suggestions for a more comprehensive test.
```slog
; Strings with spaces
(strs 1 "well string")
(strs 2 "well another string)")
(strs 3 "yet another ! ? string")

[(strs _ str_val) --> (just_str str_val)]
```

**Comment by StarGazerM** [comment]
can you add the testcase in https://github.com/harp-lab/slog-lang1/tree/master/slog/tests/testcase , there is some CI script could read in  test case there

**Comment by sowmith1999** [comment]
This commit has that added and the script is able to pick it up

https://github.com/harp-lab/slog-lang1/commit/eb8e1e7f2e8a6a3bb6a2670a507ef48d911ff84c

**Comment by sowmith1999** [comment]
This commit only supports strings when loaded from the slog file and fails when loaded from csv files, as does the main branch.

**Comment by sowmith1999** [comment]
#49 Issue is also also worked in this PR, along with support for spaces in strings

**Comment by sowmith1999** [comment]
@StarGazerM Strings from fact files work, CI test goes through. Please let me know if there is any concern.

**Pull request merged**
